---

- name: Create ansible directories
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ win_temp_dir }}"
    - "{{ win_log_dir }}"

- name: Import windows-powershell
  ansible.builtin.import_tasks: windows-powershell.yml

## Powershell profile
## https://www.fireeye.com/blog/threat-research/2016/02/greater_visibilityt.html
## http://fr.slideshare.net/Hackerhurricane/ask-aalware-archaeologist/25
## https://logrhythm.com/fr/blog/powershell-command-line-logging/
## FIXME! french characters issue in path?
- name: Set powershell profile
  ansible.windows.win_template:
    src: Profile.ps1.j2
    dest: 'c:\windows\system32\WindowsPowershell\v1.0\Profile.ps1'
#  ignore_errors: true

# https://gallery.technet.microsoft.com/scriptcenter/2d191bcd-3308-4edd-9de2-88dff796b0bc
- name: Download Windows Update PowerShell Module
  ansible.windows.win_get_url:
    url: 'https://gallery.technet.microsoft.com/scriptcenter/2d191bcd-3308-4edd-9de2-88dff796b0bc/file/41459/43/PSWindowsUpdate.zip'
    dest: "{{ win_temp_dir }}\\PSWindowsUpdate.zip"

- name: Import windows-psmodules
  ansible.builtin.import_tasks: windows-psmodules.yml
  when: win_powershellmodules != []
