---

- name: Temporarily trust PSGallery repository
  ansible.windows.win_shell: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

- name: Install desired Powershell modules
  ansible.windows.win_shell: "Install-Module {{ item }}"
  with_items: "{{ win_powershellmodules }}"

- name: Untrust PSGallery repository
  ansible.windows.win_shell: Set-PSRepository -Name PSGallery -InstallationPolicy Untrusted
